In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 33.9 ms


In [3]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 1.76 s


In [4]:
data = np.random.randn(2,3)

In [5]:
data

array([[-2.72506201, -0.28588212,  0.76055275],
       [ 0.65358456,  0.47978495, -0.16349276]])

In [6]:
data*10

array([[-27.25062013,  -2.85882121,   7.60552749],
       [  6.53584559,   4.79784954,  -1.63492759]])

In [7]:
data+data

array([[-5.45012403, -0.57176424,  1.5211055 ],
       [ 1.30716912,  0.95956991, -0.32698552]])

In [8]:
data.shape

# 차원의 크기를 알려주는 shape라는 튜플

(2, 3)

In [9]:
data.dtype


#자료형을 알려주는 dtype라는 객체

dtype('float64')

In [10]:
data1 =[6,7,5,8,0,1]
arr1=np.array(data1)

In [11]:
arr1

array([6, 7, 5, 8, 0, 1])

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim


#배열의 차원 수 or 배열의 축 수

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np,arange(15)

NameError: name 'arange' is not defined

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [24]:
arr2 = np.array([1,2,3],dtype=np.int32)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
arr.dtype

dtype('int32')

In [29]:
float_arr =arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
float_arr

array([1., 2., 3., 4., 5.])

In [32]:
arr = np.array([3.7-1.2-2.6,0.5,12.9,10.1])

In [33]:
arr

array([-0.1,  0.5, 12.9, 10.1])

In [34]:
arr.astype(np.int32)

array([ 0,  0, 12, 10])

In [35]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [36]:
numeric_strings.astype(float)


#np.float64 형태로 입력하여도 무방

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

In [38]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [40]:
int_array. astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_uint= np.empty(8, dtype='u4')

In [42]:
empty_uint32= np.empty(8, dtype='u4')

In [43]:
empty_unit32


#empty는 초기화되지 않은 값으로 zeros나 ones와 마찬가지로 배열을 생성

#주의해야 할 것은 메모리도 초기화되지 않기 때문에 예상하지 못한 쓰레기 값이 들어가 있음.

NameError: name 'empty_unit32' is not defined

In [44]:
arr = np.array([[1.,2.,3.,],[4.,5.,6.,]])

In [45]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [47]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr**0.5


# **은 거듭제곱 연산자

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
arr2 =np.array([[0.,4.,1.],[7.,2.,12.]])

In [51]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [52]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [53]:
arr= np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [57]:
arr[5:8]=12


#배열조각에 스칼라값을 대입하면 선택영역전체로 전파(브로드캐스팅)

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]

In [60]:
arr_slice

array([12, 12, 12])

In [61]:
arr_slice[1] =12345

In [62]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [63]:
arr_slice

array([   12, 12345,    12])

In [64]:
arr_slice[:] = 64

# : 배열의 모든값을 할당

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0,2]

3

In [70]:
arr3d = np.array([[[1,2,3],[4,5,6],[[7,8,9],[10,11,12]]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-70-d03aff9f7417>, line 1)

In [71]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [72]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()

In [75]:
arr3d[0]=42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[1,0]

array([7, 8, 9])

In [80]:
x=arr3d[1]

In [81]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [82]:
x[0]

array([7, 8, 9])

In [83]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [84]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1,:2]

array([4, 5])

In [89]:
arr2d[:2,2]

array([3, 6])

In [90]:
arr2d{:,:1}

SyntaxError: invalid syntax (<ipython-input-90-7102c1e82f3a>, line 1)

In [91]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [92]:
arr2d[:2, 1:] =0

In [93]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [94]:
names = np.array(['Bob',"Joe",'Will','Bob','Will','Joe','Joe'])

In [95]:
data = np.random.randn(7.4)

TypeError: 'float' object cannot be interpreted as an integer

In [96]:
data = np.random.randn(7,4)

In [97]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [98]:
data

array([[-0.19308602,  0.55232016, -0.76855765,  0.6032551 ],
       [ 0.43843396,  0.20162333, -1.81594992,  1.4064968 ],
       [-0.45799531,  0.30172715,  1.52561951,  0.85150768],
       [-0.41202334, -0.95917085, -0.8925575 , -0.50724202],
       [-0.53062443,  1.12390423,  1.34217207,  0.47728778],
       [-1.10231668,  1.9180969 ,  0.87423257, -0.81278512],
       [-0.98013442, -0.02102004, -1.73194495, -0.99932815]])

In [99]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [100]:
data[names =='Bob']

array([[-0.19308602,  0.55232016, -0.76855765,  0.6032551 ],
       [-0.41202334, -0.95917085, -0.8925575 , -0.50724202]])

In [101]:
data[names == 'Joe']

array([[ 0.43843396,  0.20162333, -1.81594992,  1.4064968 ],
       [-1.10231668,  1.9180969 ,  0.87423257, -0.81278512],
       [-0.98013442, -0.02102004, -1.73194495, -0.99932815]])

In [102]:
data[names == 'Bob', 2:]

array([[-0.76855765,  0.6032551 ],
       [-0.8925575 , -0.50724202]])

In [103]:
data[names =='Bob',3]

array([ 0.6032551 , -0.50724202])

In [104]:
names |='Bob'


# /=부정 (집합기호로 ~의 의미와 동)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [105]:
names |='Bob'


# I=부정 (집합기호로 ~의 의미와 동)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [106]:
names |= 'Bob'


# l=부정 (집합기호로 ~의 의미와 동)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [108]:
names |= 'Bob'


#  !=부정 (집합기호로 ~의 의미와 동)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [109]:
names != 'Bob'


#  !=부정 (집합기호로 ~의 의미와 동)

array([False,  True,  True, False,  True,  True,  True])

In [110]:
data[~(names == 'Bob')]

array([[ 0.43843396,  0.20162333, -1.81594992,  1.4064968 ],
       [-0.45799531,  0.30172715,  1.52561951,  0.85150768],
       [-0.53062443,  1.12390423,  1.34217207,  0.47728778],
       [-1.10231668,  1.9180969 ,  0.87423257, -0.81278512],
       [-0.98013442, -0.02102004, -1.73194495, -0.99932815]])

In [111]:
cond = names =='Bob'

In [112]:
data[~cond]

array([[ 0.43843396,  0.20162333, -1.81594992,  1.4064968 ],
       [-0.45799531,  0.30172715,  1.52561951,  0.85150768],
       [-0.53062443,  1.12390423,  1.34217207,  0.47728778],
       [-1.10231668,  1.9180969 ,  0.87423257, -0.81278512],
       [-0.98013442, -0.02102004, -1.73194495, -0.99932815]])

In [113]:
mask = (names == 'Bob')|(names == 'Will')


#두가지 이상을 사용하고 싶을경우 &(and) 나 /(or)과 같은 논리 연산자 사용

In [114]:
mask

array([ True, False,  True,  True,  True, False, False])

In [115]:
mask = (names == 'Bob')|(names == 'will')


#두가지 이상을 사용하고싶을경우 &(and) 나 /(or)과 같은 논리 연산자 사용

In [116]:
mask

array([ True, False, False,  True, False, False, False])

In [117]:
data[mask]

array([[-0.19308602,  0.55232016, -0.76855765,  0.6032551 ],
       [-0.41202334, -0.95917085, -0.8925575 , -0.50724202]])

In [118]:
data[data<0] =0

In [119]:
data

array([[0.        , 0.55232016, 0.        , 0.6032551 ],
       [0.43843396, 0.20162333, 0.        , 1.4064968 ],
       [0.        , 0.30172715, 1.52561951, 0.85150768],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.12390423, 1.34217207, 0.47728778],
       [0.        , 1.9180969 , 0.87423257, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [120]:
arr=np.empty((8,4))

In [121]:
for i in range(8):
    arr[i] = i

In [122]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [123]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [124]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [125]:
arr=np.arange(32).reshape((8.4))

TypeError: 'float' object cannot be interpreted as an integer

In [126]:
arr = np.arange(32).reshape((8,4))

In [127]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [128]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [129]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [130]:
arr = np.arange(15).reshape(3.5)

TypeError: 'float' object cannot be interpreted as an integer

In [131]:
arr = np.arange(15).reshape(3,5)

In [132]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [133]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [134]:
arr = np.random.randn(6,3)

In [135]:
arr

array([[ 0.75883676, -1.34628283,  0.27475696],
       [ 1.72705598,  0.76204811, -0.8945404 ],
       [ 0.59392753,  0.61932722,  0.6239363 ],
       [-1.54853172, -1.25186279,  0.57951674],
       [-1.41585101, -0.87300517,  1.04335141],
       [ 1.27649463, -0.57767296,  1.16773091]])

In [136]:
np.dot(arr.T,arr)


#행렬의 내적 (크게 다루지는 않을 듯..ㅇㅅㅇ..)

array([[ 9.94332862,  3.0995244 , -1.84988068],
       [ 3.0995244 ,  5.43976548, -2.97605585],
       [-1.84988068, -2.97605585,  4.0530077 ]])

In [137]:
arr=np.arange(16).reshape((2,2,4))

In [138]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [139]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [140]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [141]:
arr=np.arange(10)

In [142]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.sqrt(arr)


#sqrt :제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [144]:
np.exp(arr)


#자연상수e에 대한 arr원소들의 제곱

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [145]:
x=np.random.randn(8)

In [146]:
y=np.random.randn(8)

In [147]:
x

array([0.42390831, 0.5593611 , 0.23678032, 0.25509054, 1.38345393,
       0.26824461, 0.54889496, 0.16902032])

In [148]:
y

array([ 1.64593921,  0.01590517,  1.0086835 , -0.27398458, -0.11339373,
        0.17924822,  0.78413647, -0.21817681])

In [149]:
np.maximum(x,y)

array([1.64593921, 0.5593611 , 1.0086835 , 0.25509054, 1.38345393,
       0.26824461, 0.78413647, 0.16902032])

In [150]:
arr = np.random.randn(7)*5

In [151]:
arr

array([-1.18325352,  7.04119038, 14.2268739 , -3.37401172, -5.37702615,
       -0.36910752, -2.29799247])

In [152]:
remainder,whole_part = np.modf(arr)

In [153]:
remainder

array([-0.18325352,  0.04119038,  0.2268739 , -0.37401172, -0.37702615,
       -0.36910752, -0.29799247])

In [154]:
whole_part

array([-1.,  7., 14., -3., -5., -0., -2.])

In [155]:
arr

array([-1.18325352,  7.04119038, 14.2268739 , -3.37401172, -5.37702615,
       -0.36910752, -2.29799247])

In [156]:
np.sqrt(arr)

<ipython-input-156-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 2.65352414, 3.77185285,        nan,        nan,
              nan,        nan])

In [157]:
np.sqrt(arr,arr)

<ipython-input-157-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([       nan, 2.65352414, 3.77185285,        nan,        nan,
              nan,        nan])

In [158]:
arr

array([       nan, 2.65352414, 3.77185285,        nan,        nan,
              nan,        nan])

In [1]:
s\
a

SyntaxError: invalid syntax (<ipython-input-1-774467e00b4e>, line 2)